# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DragItems' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks! # Add this if you are targeting iOS 8+ or using Swift

  # Fundamental
  pod 'RxSwift',    '~> 4.0'            		        # RxSwift
  pod 'RxCocoa',    '~> 4.0' 

  # UI
  pod 'JZCalendarWeekView', '0.5.1'                     	# Calendar view

end
